import React from 'react';
import { Section } from './Section';
import { User, Users, Briefcase } from 'lucide-react';
import { UseCase } from '../types';

const cases: UseCase[] = [
  {
    title: "For Founders",
    description: "Validate a napkin sketch before building the MVP. Understand the 'why' and 'who' before writing a single line of code.",
    icon: <User className="h-6 w-6 text-indigo-600" />
  },
  {
    title: "For Product Teams",
    description: "Explore adjacent features or new product lines without distracting the core team from the current roadmap.",
    icon: <Users className="h-6 w-6 text-teal-600" />
  },
  {
    title: "For Innovation Labs",
    description: "Map complex opportunity spaces and generate defensible business cases for stakeholder approval.",
    icon: <Briefcase className="h-6 w-6 text-blue-600" />
  }
];

export const UseCases: React.FC = () => {
  return (
    <Section id="use-cases" background="white">
      <div className="grid lg:grid-cols-2 gap-16 items-center">
        <div>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-slate-900 mb-6">
            Designed for those who <br /> build the future.
          </h2>
          <p className="text-lg text-slate-600 mb-8 max-w-md">
            Whether you are a solo operator or leading a corporate venture arm, clarity is your most valuable asset.
          </p>
          <div className="space-y-6">
            {cases.map((useCase, idx) => (
              <div key={idx} className="flex gap-4 group">
                <div className="flex-shrink-0 mt-1 p-2 bg-gray-50 rounded-lg group-hover:bg-gray-100 transition-colors">
                  {useCase.icon}
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 mb-1">{useCase.title}</h3>
                  <p className="text-slate-600 text-sm leading-relaxed">{useCase.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
        
        {/* Abstract Visual Representation of the Report/Dashboard */}
        <div className="bg-slate-50 rounded-2xl p-8 border border-gray-100 shadow-sm relative overflow-hidden">
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10"></div>
          <div className="relative bg-white rounded-xl shadow-lg border border-gray-200 p-6 max-w-md mx-auto transform rotate-1 hover:rotate-0 transition-transform duration-500">
            <div className="h-4 w-1/3 bg-slate-200 rounded mb-4"></div>
            <div className="space-y-2 mb-8">
              <div className="h-2 w-full bg-gray-100 rounded"></div>
              <div className="h-2 w-5/6 bg-gray-100 rounded"></div>
              <div className="h-2 w-4/6 bg-gray-100 rounded"></div>
            </div>
            
            <div className="grid grid-cols-2 gap-4 mb-6">
              <div className="bg-blue-50 p-4 rounded-lg border border-blue-100">
                <div className="h-8 w-8 bg-blue-100 rounded-full mb-2 flex items-center justify-center text-blue-600 font-bold text-xs">85%</div>
                <div className="h-2 w-16 bg-blue-200 rounded"></div>
              </div>
              <div className="bg-indigo-50 p-4 rounded-lg border border-indigo-100">
                <div className="h-8 w-8 bg-indigo-100 rounded-full mb-2 flex items-center justify-center text-indigo-600 font-bold text-xs">A+</div>
                <div className="h-2 w-16 bg-indigo-200 rounded"></div>
              </div>
            </div>

            <div className="flex items-center gap-2 text-xs text-slate-400">
               <div className="h-2 w-2 rounded-full bg-green-500"></div>
               Generated by ParallelFoundry
            </div>
          </div>
        </div>
      </div>
    </Section>
  );
};